### ISSUE TITLE
Updating Latitude/Longitude on the profile page using "," as decimal separator gives error 500

### ISSUE THREAD

**Issue by kiwnix** [fedora-infra/fas#118]
When you update your location (Latitude and Longitude fields) using "," as a decimal separator, the server returns an error 500 and do not update the profile, if you use "." as the decimal separator it updates the profile OK.

Locales tested: en, es

**Comment by ryanlerch** [comment]
In FAS3, if you try to update your location using the comma as a decimal seperator, it no longer returns a 500 error, just informs you that the number inputted is not a decimal number.
