### ISSUE TITLE
Wrap text w/ SSH Key

### ISSUE THREAD

**Issue by Cydrobolt** [fedora-infra/fas#126]
The current "My account" section shows the SSH key on a single line, but this causes the page to stretch a lot to the right. Enabling text-wrapping on the SSH key would be beneficial.

**Comment by ralphbean** [comment]
Is this a FAS3 issue or a FAS2 issue?

**Comment by Cydrobolt** [comment]
It is an issue in the current FAS, probably FAS2?

**Comment by Cydrobolt** [comment]
After: 
![image](https://cloud.githubusercontent.com/assets/1058150/7524953/75032554-f4d3-11e4-8e34-7152093ff9d1.png)

**Comment by ralphbean** [comment]
> It is an issue in the current FAS, probably FAS2?

yes, FAS2 in that case.  :)
