### ISSUE TITLE
Missing details in "Fedora Account Data Update" email

### ISSUE THREAD

**Issue by nixpanic** [fedora-infra/fas#133]
I have just updated my email in my Fedora Account. An email got sent out to the old address with a notification, all seems well.

However, the new email address is not listed in the email that should show the changes? No email address is displayed there at all.

It is good to have the notification of the change sent to the old address, but it surely should include the changed address :-)

**Comment by laxathom** [comment]
There's a dedicated email notification when you update your email which requires you to confirm the change.
The use-case from where you can have the "Fedora account data update" notification is when you update more than one personal info from your account which, actually led me to see something not handled correctly at this stage of update.

Could you confirm me that is what you did, changed more than one info or as you just said, your email only?

**Comment by nixpanic** [comment]
As far as I remember I did change my email only. There was a confirmation sent to the new updated for accepting the change. However, the old address got a notification about the change (GOOD), but that notification did not contain the updated, or any email address (BAD).

Thanks!

**Comment by puiterwijk** [comment]
So the fact that the change email to your old address did not include the new email address makes sense, as the address hasn't been changed yet (it needs confirmation before that happens), but I agree it's confusing.

Are you sure you didn't also get a separate email on your old address telling you the email address was changed?

**Comment by nixpanic** [comment]
> So the fact that the change email to your old address did not include the new email address makes sense, as the address hasn't been changed yet (it needs confirmation before that happens), but I agree it's confusing.

Oh, indeed, very confusing. Confusing enough to raise the concern. Its rather an important change, and the new email address should definitely be listed with a note like "pending confirmation" or something.

> Are you sure you didn't also get a separate email on your old address telling you the email address was changed?

I just checked, and I only see the 1st email with subject "Fedora Account Data Update devos" on my old email address. I might have deleted a confirmation, but would normally wait with that until this discussion has finished.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
