### ISSUE TITLE
[l10n] Localization is lost on login

### ISSUE THREAD

**Issue by Jibec** [fedora-infra/fas#139]
Hi,
1/ https://admin.fedoraproject.org/accounts/
2/ select "fr" for locale
3/ login
4/ text is in English because my profile default is "locale=en"

=> I find weird

can we make those fix ? 
- if set, continue use the locale set on welcome page
- add explicitly the locale on https://admin.fedoraproject.org/accounts/user/view/jibecfed so user understand the impact of setting

btw, that "locale setting" is interesting, does it have some usages in other context ?

**Comment by Jibec** [comment]
Any hope to improve this situation @ralphbean  ?

**Comment by pypingou** [comment]
@Jibec for FAS you probably want to ping @laxathom actually ;-)

**Comment by laxathom** [comment]
Hmm, why weird?
The app switches to your locale once logged in as its reads from your personal info/configuration which is higher than the default one (on welcome's page, when not logged in) and adapts its behavior and views based on that.

In the other hand, I can agree that, once logged in and then you change the locale, the app should switch to the one you selected.

> btw, that "locale setting" is interesting, does it have some usages in other context ?

It should and - I hope - will ;)
We try to make the account management more "centric" in a way that people can have one point of configuration (not for everything of course) avoiding them to update their personal/common info for each single fedora project's app.

**Comment by Jibec** [comment]
thanks for your answer @laxathom 

to make it easier to understand by users, can you please add the "locale" setting when viewing a profile ?
https://admin.fedoraproject.org/accounts/user/view/jibecfed

at the moment you need to edit your settings to see it, which make it difficult for user to understand why the language is changing before and after login.

**Comment by pypingou** [comment]
Why closing, is this fixed?

**Comment by Jibec** [comment]
I understand a FAS rewrite is going on and I already asked to be able to translate it: https://github.com/fedora-infra/fas/issues/142

If this little issue hasn't been fixed in a year, it may mean there is not sufficient ressources or that the modification isn't so easy to fix or whatever else.

In addition, I understood after this ticket that Fedora contributor tools are pretty much unstranslated on purpose (it cost and english is the working language).

As this isn't a huge issue, I prefer to close it. We'll discuss this once FAS3 is ready. Is it OK for you?

**Comment by laxathom** [comment]
works for me.
