### ISSUE TITLE
[FAS3] DB mode inconsistencies

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fas#160]
* people_acticity_log has a field timestamp while all the other timestamps specify of what they're a timestamp of
* group_membership has a sponsor field which is a foreign key, shouldn't it sponsor_id?
* group_membership has a field approval_timestamp, since it could be approval or removal, should we rename it update_timestamp as we have for others?
* group has a field certificate which is a foreign key, shouldn't it be certificate_id?
* group has a field update*d*_timestamp while others have update_timestamp, typo?
* account_permissions has a field people while other tables use person_id, should we change account_permissions?
* clients_certificates has a field people while other tables use person_id, should we change clients_certificates?
* clients_certificates refers to clients in its name but links people with certificates, should we rename it people_certificates?

**Comment by pypingou** [comment]
I think this one can be closed now, no?

**Comment by laxathom** [comment]
Yup. Sorry, I omitted to refers this issue in my commit
