### ISSUE TITLE
FAS3 packaging

### ISSUE THREAD

**Issue by relrod** [fedora-infra/fas#172]
This issue is for tracking.

``` irc
13:46 < stickster> relrod: Hey, I was talking with pingou earlier and he was expressing that he could use some help with FAS3 packaging. I know you have been doing some work on packaging for modernpaste, this should be relatively easier ;-)
13:47 < relrod> stickster: ok :)
13:48 < stickster> relrod: the key point being, minimally all the deps need to be in EPEL, and capable of getting a build in Koji -- preferably a real build but a scratch-build would be minimally sufficient
13:49 < relrod> stickster: alright, I'll add it to my list and see what is done/needs to be done.
```

**Comment by relrod** [comment]
I have an (untested, but building) first attempt here: http://koji.fedoraproject.org/koji/taskinfo?taskID=14590394 but it is against f23. Not sure yet if it is missing anything for epel7.

**Comment by relrod** [comment]
http://koji.fedoraproject.org/koji/taskinfo?taskID=14590511 ok it apparently builds for epel7 too, but still untested. Will do that soon.

**Comment by laxathom** [comment]
Cool!

The config file is missing from the first build. It has to be installed in `/etc/fas/production.ini`
The python-alembic is  not mandatory to run fas.

You can remove everything related to fas-client and build a new spec file in git repo fas-client.

Note, you can fire some tests after added some fake data as below (requires python-fake-factory though /me needs to make this optional in the code):
```
fas-admin --initdb --default-value

fas-admin --generate-fake-data -n 666
```

Other than that, this look good.

**Comment by pypingou** [comment]
> The python-alembic is not mandatory to run fas.

Well not to run FAS itself but pretty useful for the upgrades :)

**Comment by relrod** [comment]
@laxathom thanks for the feedback! I'll make those changes soon!

**Comment by laxathom** [comment]
Hey so, while fixing up thing and thinking on the long term of the software lifetime, I realized that as we're building a software non-fedora specific, we might also need to pull out the fedora project templates code as a subpackage `fas-templates-fedora`.

This way, it will make thing easier to only update the template when needed. The front-end - the UI - code will have its own life circle.

**Comment by pypingou** [comment]
> we might also need to pull out the fedora project templates code as a subpackage fas-templates-fedora.

Sounds like a nice idea, with two remarks:
* Probably not needed before flock (while we do need the package by then)
* if we keep the Fedora theme in the sources, then I doubt the theme will have a much different live cycle than the rest of the sources (but that remains true for other potential FAS users who will be able to more easily update their theme)

**Comment by relrod** [comment]
> You can remove everything related to fas-client and build a new spec file in git repo fas-client.

@pypingou is `fas-client` also needed for flock?

**Comment by pypingou** [comment]
@relrod for the moment just having a web ui to test/poke is sufficient for flock imho.

fas-client will be needed, but we won't be porting stg hosts to FAS3 right now anyway, so it gives us a little more time.
My idea is:
* deploy FAS3 UI
* Fix fas-client
* Fix python-fedora
* Drop FAS2 in stg
* Deploy FAS3 fas-client 
* Port broken app to new python-fedora / port apps to FAS3

How does that sound?

**Comment by ryanlerch** [comment]
FAS is now packaged. are we right to close this one off?

**Comment by laxathom** [comment]
We are. Closing
