### ISSUE TITLE
[FAS3]  Unique contrant failed on people.email when two accounts are created with exact info

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fas#178]
When creating an account with exactly the same info the program crashes to a debug screen.
What should happen is we should warn the user that the email is already taken instead.

**Comment by skrzepto** [comment]
```
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: people.email [SQL: u'INSERT INTO people (username, password, fullname, ircnick, avatar, avatar_id, introduction, postal_address, country_code, locale, birthday, birthday_month, telephone, facsimile, affiliation, bio, timezone, gpg_fingerprint, ssh_key, email, recovery_email, bugzilla_email, email_token, unverified_email, security_question, security_answer, login_attempt, password_token, old_password, certificate_serial, status, status_timestamp, privacy, email_alias, blog_rss, latitude, longitude, fas_token, github_token, twitter_token, login_timestamp, creation_timestamp, update_timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)'] [parameters: (u'simon', '$2a$10$TTUCo9EU.CI6p6Rq8GqNx.vE/oT1mIMrNVD3sdAgHPj7/uqgaMANq', u'simon', u'', u'', None, u'', u'', None, u'en_US', None, None, u'', None, None, None, u'UTC', None, None, u'simon@gmail.com', None, None, None, None, u'-', u'-', None, 'ba2eb36d81d60cf13775da80d3517eda60e74dd5', None, 1, 3, '2016-07-15 15:25:58.465140', 0, 1, None, None, None, None, None, None, '2016-07-15 15:25:58.465149')]
```

**Comment by laxathom** [comment]
Hum... this should be already handled by https://github.com/fedora-infra/fas/blob/FAS_3.0/fas/forms/people.py#L122-L128 

Need to double check then.

**Comment by skrzepto** [comment]
I know I saw that too. odd, I think It might be an string encoding problem

**Comment by skrzepto** [comment]
yea its an encoding problem

the top is the printed list of available emails while after printing `####field.data` it seems its not unicode 
```
......
a18@yahoo.com', u'aferry@gmail.com', u'ppagac@yahoo.com', u'dmills@hotmail.com', u'opurdy@gmail.com', u'lorenaziemann@hotmail.com']
####field.data
simon@gmail.com

```

**Comment by skrzepto** [comment]
Disregard my comment about unicode format issue. I confirmed that that field.data is unicode

**Comment by skrzepto** [comment]
When i wrote a unittest for this case, I can't seem to reproduce.

**Comment by skrzepto** [comment]
ahh I figured out how to reproduce the error.

When you create two accounts with exact same data then it faults like this. 

If if everything but the emails are different the there's a warning `Email: simon@gmail.com exists already!`

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
