### ISSUE TITLE
[FAS3] Unable to submit changes to profile edit

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fas#179]
## Summary
When I try to edit a profile and click submit while logged in, the app throws 401 when it shouldn't have.

## Steps to reproduce

1. Create an account and change its status `people.status` to `1`  or use the admin account with pass admin.

2. Go to edit profile

3. *Optional* edit or add data

4. Click `save changes`

then it throws a 401 error

## Expected Behavior
Either warn us that we submitted invalid data or let us know the data was succesfully saved and redirect us to the edit page again

**Comment by skrzepto** [comment]
Also unable to access `update password` and `lost password` while logged in

**Comment by skrzepto** [comment]
`edit profile` is also throwing 401 on `http://fas3-dev.fedorainfracloud.org`

**Comment by pypingou** [comment]
AFAIT this is now fix, likely by the commit referenced above
