### ISSUE TITLE
[FAS3] group name never shown?

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fas#186]
Looking at the interface, it seems we're only ever showing the display name, not the actual group name.

In relation with #166 should we either:
* Show the group name in the UI
* Link to the group using its display name

My test case is the `gitarm` group that is displayed as `arm`, so do we want to link to
* http://0.0.0.0:6543/group/details/gitarm
or 
* http://0.0.0.0:6543/group/details/arm

Thanks

**Comment by laxathom** [comment]
The UI fallbacks to group's name when no display name has been set up.
:+1:  with group's name in the route request.

**Comment by pypingou** [comment]
If we're using the name, then I'd like to adjust #188 to include that name in the group details page

**Comment by laxathom** [comment]
Yup, agreed!

**Comment by pypingou** [comment]
This got fixed in #188
