### ISSUE TITLE
Questions about FAS

### ISSUE THREAD

**Issue by Jibec** [fedora-infra/fas#204]
Hi,

I am working on new L10N groups and have a few questions about FAS.
1. Is it possible to store an information related to the user in the group ? Our use case is to store the user language membership.
   For example, I'm a sponsor (because I am a language team coordinator) and member of french team.
   Note : we can have one user in multiple teams, the fas account attribute is not sufficient.
2. can we have a L10N sponsor group who is responsible for a few user groups ?
3. would it be difficult to build something like this to extract the current active users for each translation team ? https://fedoraproject.org/wiki/Ambassadors/MembershipService/Verification
   3.1 Is it possible to have something dynamic like badges display ? (to embed it in some wiki pages)

**Comment by laxathom** [comment]
> Is it possible to store an information related to the user in the group ? Our use case is to store the user language membership.
For example, I'm a sponsor (because I am a language team coordinator) and member of french team.
Note : we can have one user in multiple teams, the fas account attribute is not sufficient.

I'm not sure to get that one. What kind of info do you want from user?

> can we have a L10N sponsor group who is responsible for a few user groups ?

That one too. you want a "parent" -> "child" group workflow here?

> would it be difficult to build something like this to extract the current active users for each translation team ? https://fedoraproject.org/wiki/Ambassadors/MembershipService/Verification
3.1 Is it possible to have something dynamic like badges display ? (to embed it in some wiki pages)

This feature has already been added to our next major release FAS 3.0. You would be able to get members' status per group. Is this what you're asking for?

**Comment by Jibec** [comment]
Thanks for your answer.
The Fedora translation project is organized by language team. I would like to store the team witch user is member of.

> That one too. you want a "parent" -> "child" group workflow here?

Yes, one FAS group having some other group rights like "sponsor" or "admin".

> This feature has already been added to our next major release FAS 3.0. You would be able to get members' status per group. Is this what you're asking for?

Yes, great ! When is it to be expected ?

**Comment by pypingou** [comment]
>>   can we have a L10N sponsor group who is responsible for a few user groups ?
> That one too. you want a "parent" -> "child" group workflow here?

I guess the RFE here is to have something more similar to an LDAP approach.
- a group for admins
- a group for sponsors
- user groups managed by the two groups mentioned above

**Comment by pypingou** [comment]
> Is it possible to store an information related to the user in the group ? Our use case is to store the user language membership.

That part I do not understand

**Comment by Jibec** [comment]
Thanks for your answer. We'll keep it simple with one single FAS group.
To know which team the user is part of, we'll use the translation platform and change our process.
