### ISSUE TITLE
if no locale setup in the ini file, can't save profile changes

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/fas#236]
Currently, the staging instance of FAS3 in for the fedoraproject does not have the locale lines in the ini file. i.e.

    locale.default = en
    locale.available = en_US,en_GB,fr

While we should probably fix that, there is no fallback if these arent set. For example, if i try to edit my details on the page, i get the following error.

![screenshot from 2017-01-20 09-51-49](https://cloud.githubusercontent.com/assets/592259/22130154/1fd4acc4-def6-11e6-8a3b-a54aefdc21b7.png)

we should either throw an error if no locales are set in the ini file, or not show / process the field at all if they arent set in the ini file.

**Comment by laxathom** [comment]
How about make this field `en_US` by default when opening the edit page?
