### ISSUE TITLE
no email verification on bugzilla email

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/fas#239]
In FAS3 we accept a bugzilla email without checking if that user has control of that email.

as such, it is possible for a user to set their bugzilla email to the email of another user. If then the actual owner of the bugzilla email / account tries to add the email to their account, when editing their profile, they get the following form validation error like:

```
Bugzilla email: <name>@<domain>.com exists already!
```

**Comment by ryanlerch** [comment]
This applies to the IRC nick too, another user can 'steal' someones IRC nick, causing them to to be able to set it in FAS

**Comment by pandyamarut** [comment]
May be once used nick , cant be used again. 
this might help. 
Look for it.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
