### ISSUE TITLE
Editing your profile page appears to timeout

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/fas#240]
1. open the page to edit your profile, i.e. http://localhost:5002/people/profile/1615
2. Wait approx > 2mins after page is loaded
3. make a change and try to submit the changes

The user is given a 401 error. However, if you load the page again, you are still logged in, and as long as you make the changes and submit them in under about 2 mins, you can edit your profile.

I can reproduce everytime on the standard FAS3 vagrant test instance.

**Comment by laxathom** [comment]
This actually is a configuration issue. You can manage session timeout from the config file.
Looks for `settion settings` in development.ini

**Comment by ryanlerch** [comment]
but what is the point of the timeout here? I am still logged in if i refresh the page.

**Comment by laxathom** [comment]
Are you refreshing the page after those 2 minutes actually?

**Comment by ryanlerch** [comment]
What i mean is that you are still logged in, even after the 2 minutes timeout. So what is the point of a timeout here, if I can just refresh the page, and then change it -- without having to enter a password or anything. All it seems to be doing is making the user fill out the form within two minutes.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
