### ISSUE TITLE
Checkboxes in Admin panel tables don't do anything

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/fas#256]
In the tables in the admin panel, there are checkboxes on the left sides of the tables that don't appear to do anything, You can check them, but no interface for editing multiple items is present.

These should be removed until we implement multiple field editing.

![checkboxes](https://cloud.githubusercontent.com/assets/592259/22545689/6fdae79e-e985-11e6-8a65-7e9097a311a8.png)

**Comment by laxathom** [comment]
> These should be removed until we implement multiple field editing.

Agreed.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
