### ISSUE TITLE
Private Group Support

### ISSUE THREAD

**Issue by bexelbie** [fedora-infra/fas#259]
With the new FAS we need to be able to support private groups where membership in the group is not public.  No use case has been suggested during brainstorming where the group's existance needs to be hidden, however membership is definitely not to be exposed.

Is this on the roadmap?

**Comment by laxathom** [comment]
It is implemented already and part of first major release 3.0, so yes :)

The group is only view-able by its approved members and system's admins.

**Comment by bexelbie** [comment]
Is the group set to prevent members from seeing each other?

**Comment by laxathom** [comment]
Nope.
Only the group is private not membership.

**Comment by bexelbie** [comment]
Is it reasonable to scope this feature?

**Comment by laxathom** [comment]
I'm trying to understand the idea of having a private group with members that can't see each other specifically from group POV.

**Comment by bexelbie** [comment]
The group is used for administrative purposes and not for communication purposes.  In this case we are considering have a group for people whose funding requests require extra processing for various reasons.  The fact that any individual needs this is a private matter between this individual and the funders, but we want a way to track them in a reliable and durable manner.  This was the suggested method.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
