### ISSUE TITLE
Add support for ecdsa ssh key.

### ISSUE THREAD

**Issue by laxathom** [fedora-infra/fas#60]
See: https://fedorahosted.org/fas/ticket/172

We can do this by adding the keyword to the regex's list in ValidSSHKey validator.

**Comment by br0ziliy** [comment]
@laxathom should this one be closed, since this is implemented in #75 ?

**Comment by Akasurde** [comment]
We can close this since #75 is merged.

**Comment by ralphbean** [comment]
Thanks all!
