### ISSUE TITLE
Groups' management

### ISSUE THREAD

**Issue by laxathom** [fedora-infra/fas#80]
Groups' management re-design:
- Will inherit standard features from fas2 (with wording updates)
- Group status. Account's admin will be able to:
  - block
  - archive
  - active
  - mute (group can still be managed by group's admin. However, no updated infos will be sent out, no emails, nor sync with fas-client or any 3rd parties, etc).
- Create or set group as private that only members and account's admin can see.
- Can Delete groups (if empty only and/or no child groups): only by account's admin.
- When applying (requesting membership) to a group, offer user to send an (optional) introduction with a modal form. 
- License agreement signing is tied to group membership, no more from profile's page. User can join a group without having to sign license agreement if it's not required.
- Membership notifications
  - Send email (via pyramid's event mechanism?) to members if status or infos get changed.
  - Send email when someone left/join a group (email sent to registered mailing list).
- Offer to principal_admin (previously, group's owner) a way to pass along its ownership to other admin's members (account's admin have this power too): use modal form.
- Filter role type from members list (all, sponsor, admin).
- Request group creation form. Once done, group admin and editors will received an email to approve the new group. Requester will receive an email if approved.

Those are my notes that I save here to track related commits

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
