### ISSUE TITLE
in the account page there is no mention of the koji certificate renewal

### ISSUE THREAD

**Issue by nmav** [fedora-infra/fas#99]
I had my koji certificate revoked for some reason and I needed to renew it. All account settings are typically in the account page: https://admin.fedoraproject.org/accounts/user/view/xuser . That includes ssh keys etc.

However, the koji keys, or documentation on how to renew them is not there. I believe that this is an omission, which if added it would simplify by moving all account info to a single page.
https://fedoraproject.org/wiki/Using_the_Koji_build_system

**Comment by pypingou** [comment]
Certificates are not handled by FAS anymore, now all the management is done via ``fedora-cert`` which has the ``-v`` (verify) and ``-n`` (new) options.

**Comment by nmav** [comment]
Is there an issue with mentioning that in the FAS page?

**Comment by pypingou** [comment]
I've nothing against :-)

**Comment by laxathom** [comment]
Client certificates are still handled by FAS. We disabled the link to generate certs from profile's page.

I do agree that infos are not clear on that as anyone can request a certificate event if the person not 
in any group but cla_done (License agreement signed).

I think this infos should be related to the packager's group and not coming from profile's page.
Maybe, add more details into "welcome message" about it.

That also why we make people use fedora-cert which comes with fedora-packager's tool as it make
more sense.

**Comment by nmav** [comment]
To be honest I don't understand what you suggest. I don't know much about the internals of Fedora infrastructure, but I use it to submit code and builds. It is awkward to go the FAS profile page to renew my SSH keys to submit code, but have to search to google on how to renew my certificate for building the code I submit. You know the details of it, and I understand it, but infrastructure is good when I don't have to know about it.

**Comment by ryanlerch** [comment]
Closing this issue as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this issue is a Feature Request that you forsee might be beneficial to Fedora Accounts, please refile it against [Noggin](https://github.com/fedora-infra/noggin)
